title: "Asif Ali Zelab Gul"
description: "Energy Systems Engineer | Portfolio"
baseurl: "/portfolio"
url: "https://asifaligul.github.io"
repository: asifaligul/portfolio
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: "Asif Ali Zelab Gul"
  avatar: "/assets/images/Profilepic.png"
  bio: "Master’s in Energy Systems | Aspiring Energy Engineer & Researcher"
  location: "Chicago, IL"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:alikhaxxn@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/asif-ali-rit"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/asifaligul"
    - label: "Resume (PDF)"
      icon: "fas fa-file-pdf"
      url: "/assets/latestresume.pdf"

minimal_mistakes_skin: "dark"
search: true

navigation:
  - title: "Home"
    url: /portfolio/
  - title: "Projects"
    url: /portfolio/projects/
  - title: "Resume"
    url: /assets/latestresume.pdf
  - title: "Contact"
    url: /portfolio/contact/

# Enable site-wide search and dark mode toggle
minimal_mistakes_skin: "dark"
search: true
